name: Build Mod
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Fix gradlew.bat permissions
        run: |
          # 修复 Windows 执行权限
          icacls gradlew.bat /grant Everyone:F
          # 确保换行符为 CRLF
          (Get-Content gradlew.bat) -replace "`n", "`r`n" | Set-Content gradlew.bat -Force

      - name: Build with Gradle
        run: .\gradlew.bat build --no-daemon
        env:
          JAVA_OPTS: "-Dfile.encoding=UTF-8"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TranslatorMod-Jars
          path: build/libs/*.jar
